demo of a dynamical graph simulator.
wiggums-analytics/mlfaker pull request #7
Opened 2021-04-06 02:58 UTC by tomNummy

# Context
This is a demo of how I would approach coding up a dynamic (directed, possibly cyclic)
graph. Leaving this as a draft PR for now to spur some discussion.

Because the graph has cycles, so there is no concept of a "source".
Therefore the entire graph must be initialized with state and that state evolved over
discrete time steps.

Here I'm just going to implement 2 simple examples of linear non-categorical graphs
where the nodes are just linear functions of their inputs. This framework can be
extended to include more complicated node functions that can involve stateful internal
parameters

# Untested

This is all untested.

2021-04-10 20:10 UTC, mstefferson reviewed
This is looking good, but I'm gonna need to do another pass (and run the code) to fully grok this. Left some comments for now.

2021-04-10 20:10 UTC, mstefferson commented on mlfaker/demo_dynamics.py
> +    def interact(self, *args, **kwargs) -> Any:
Not clear what this would be used for. Updating the Node values?

2021-04-10 20:10 UTC, mstefferson commented on mlfaker/demo_dynamics.py
> +    def interact(self, *args, **kwargs) -> Any:
Is this like a TODO (I need to to this) or are you saying with this an abstract method?

2021-04-10 20:10 UTC, mstefferson commented on mlfaker/demo_dynamics.py
> +        self.adj = {}
what is this?

2021-04-10 20:10 UTC, mstefferson commented on mlfaker/demo_dynamics.py
> +        self.add_node(u)
Should we also be adding nodes here? What if I already added two nodes and just wanted to add an edge? Should I only be using `dg.add_node` for unconnnected nodes?

2021-04-10 20:10 UTC, mstefferson commented on mlfaker/demo_dynamics.py
> +        self._reset()
Why are we resetting the nodes here?

2021-04-10 20:10 UTC, mstefferson commented on mlfaker/demo_dynamics.py
> +                self.M[i][self.N[v]] = w
`super()._build()`?

2021-04-10 20:10 UTC, mstefferson commented on mlfaker/demo_dynamics.py
> +        degrees = np.sum(self.M, axis=1)
Can you comment what `degrees` correspond to?

2021-04-10 20:10 UTC, mstefferson commented on mlfaker/demo_dynamics.py
> +    G.add_edge(a, b)
No weights?

2021-04-10 20:10 UTC, mstefferson commented on mlfaker/demo_dynamics.py
> +    M:
I'm a little confused by `M` vs `self.adj`

2021-04-10 20:10 UTC, mstefferson commented
You should rebase off `master`

2021-04-16 20:50 UTC, mstefferson commented on mlfaker/demo_dynamics.py
> +    print("\n\n 2 state heat flow system \n\n")
nit: 3

2021-04-16 20:53 UTC, mstefferson commented on mlfaker/demo_dynamics.py
> +    graph: DynamicGraph
The difference between graph/state is a little confusing to me. The state is the nodes of the graph, no?

2021-04-16 20:57 UTC, tomNummy commented on mlfaker/demo_dynamics.py
> +        self.adj = {}
the adjacency dict for the graph. if a node is in the adjacency list of another, they are connected by an edge.

2021-04-16 20:58 UTC, tomNummy commented on mlfaker/demo_dynamics.py
> +        self._reset()
that reset doesn't effect the nodes, it means that we have to rebuild the underlying matrix because the index order might have changed.

2021-04-16 21:01 UTC, tomNummy commented on mlfaker/demo_dynamics.py
> +    M:
`M` is a matrix that exists only on this subclass for performance reasons. For linear graphs, evolution boils down to matrix multiplication. I could write for loops and do the multiplication that way but it would be much slower. This is a special case for linear graphs.

2021-04-16 21:02 UTC, tomNummy commented on mlfaker/demo_dynamics.py
> +        degrees = np.sum(self.M, axis=1)
degrees is the degree matrix of the graph. (number of connections a node has)

2021-04-16 21:04 UTC, tomNummy commented on mlfaker/demo_dynamics.py
> +    graph: DynamicGraph
the graph is a collection of variables, state is the collective state that each one of those variables is in. in other words, what value the variable currently is.

2021-04-16 21:05 UTC, tomNummy commented on mlfaker/demo_dynamics.py
> +                self.M[i][self.N[v]] = w
yea that could work

2021-04-16 21:27 UTC, mstefferson reviewed
It took me a bit to figure out. Nodes of graphs are just labels. Values are given by state vectors. I think a bit more documentation could help newbs like me.

2021-04-16 21:27 UTC, mstefferson commented on mlfaker/demo_dynamics.py
> +    """Assumes each node's fucntion output is a linear sum of it's inputs.
function

2021-04-16 21:27 UTC, mstefferson commented on mlfaker/demo_dynamics.py
> +        self._reset()
I think I see. If the graph changes, you set `M`, `N` to none then rebuild when it's time to evolve

2021-04-16 21:27 UTC, mstefferson commented on mlfaker/demo_dynamics.py
> +        self.M -= np.diag(degrees)
Ya, this is not clear to me how this corresponds to the diffusion propagator

2021-04-16 21:27 UTC, mstefferson commented on mlfaker/demo_dynamics.py
> +        return state + delta / len(self.N)
can you comment on why `len(self.N)`

2021-04-16 21:28 UTC, mstefferson commented on mlfaker/demo_dynamics.py
> +    G.add_edge(c, a)
I printed out the `M` for this graph:

<img width="151" alt="image" src="https://user-images.githubusercontent.com/12516153/115085764-4f89a280-9ec8-11eb-80f4-3ca316c2ee8f.png">

2021-04-16 21:29 UTC, mstefferson commented on mlfaker/demo_dynamics.py
> +    G.add_edge(c, a)
I was expecting:
```
[[-1, 1, 1],
 [ 1 , -1, 0],
 [1,  0, -1]
 ``

2021-04-16 21:30 UTC, mstefferson commented on mlfaker/demo_dynamics.py
> +    G.add_edge(c, a)
Here's the adjacency, shouldn't there be four entries here? 
<img width="643" alt="image" src="https://user-images.githubusercontent.com/12516153/115086005-b1e2a300-9ec8-11eb-965e-040ae2b86778.png">

2021-04-16 21:36 UTC, mstefferson commented on mlfaker/demo_dynamics.py
> +        if u in self.adj:
bug: `if u.uid in self.adj`

2021-04-16 21:37 UTC, mstefferson requested changes
Buggy found https://github.com/wiggums-analytics/mlfaker/pull/7/files#r615133693

2021-04-16 21:37 UTC, mstefferson commented on mlfaker/demo_dynamics.py
> +    G.add_edge(c, a)
found the bug; https://github.com/wiggums-analytics/mlfaker/pull/7/files#r615133693

2021-04-16 21:38 UTC, mstefferson commented on mlfaker/demo_dynamics.py
> +        self.adj = {}
👍

2021-04-16 21:41 UTC, mstefferson commented on mlfaker/demo_dynamics.py
> +    graph: DynamicGraph
I see, that took me a bit to figure out. I assumed the nodes were the state

2021-04-16 21:42 UTC, mstefferson commented on mlfaker/demo_dynamics.py
> +        degrees = np.sum(self.M, axis=1)
I would comment this in the code

2021-04-16 21:43 UTC, mstefferson commented
This is some great stuff. I think a little more comments would help. I found one bug that should be addressed, but I think is enough to build off of.

2021-04-16 21:53 UTC, mstefferson commented on mlfaker/demo_dynamics.py
> +                self.M[i][self.N[v]] = w
If we trust the parent, probably don't want to dup

2021-09-07 18:23 UTC, closed without merging